#contains a dictionary of all the potential features that can be extracted
#each feature in turn contains a dictionary of its salient features:
#feature_id:
#    name: descriptive name of feature,
#    filename: filename containing feature script without extension,
#    extension: either .sql or .py,
#    default: default value of feature,
#    dependencies: later features that depend on this extraction being run first,
#    desc: description of what this feature is looking at
featureDict = {
     1:  {'name': "dropout",
         'filename': 'populate_feature_1_dropout',
         'extension': '.sql',
         'default': 0,
         'dependencies':[],
         'desc': 'none'},
     2:  {'name': "sum_observed_events_duration",
         'filename': 'populate_feature_2_sum_observed_events_duration',
         'extension': '.sql',
         'default': 0,
         'dependencies':[10],
         'desc': 'none'},
     3:  {'name': "number_of_forum_posts",
         'filename': 'populate_feature_3_number_of_forum_posts',
         'extension': '.sql',
         'default': 0,
         'dependencies':[103],
         'desc': 'none'},
     4:  {'name': "number_of_wiki_edits",
         'filename': 'populate_feature_4_number_of_wiki_edits',
         'extension': '.sql',
         'default': 0,
         'dependencies':[104],
         'desc': 'none'},
     5:  {'name': "average_length_of_forum_posts",
         'filename': 'populate_feature_5_average_length_of_forum_posts',
         'extension': '.sql',
         'default': 0,
         'dependencies':[105],
         'desc': 'none'},
     6:  {'name': "distinct_attempts",
         'filename': 'populate_feature_6_distinct_attempts',
         'extension': '.sql',
         'default': 0,
         'dependencies':[11,111],
         'desc': 'none'},
     7:  {'name': "number_of_attempts",
         'filename': 'populate_feature_7_number_of_attempts',
         'extension': '.sql',
         'default': 0,
         'dependencies':[209],
         'desc': 'none'},
     8:  {'name': "distinct_problems_correct",
         'filename': 'populate_feature_8_distinct_problems_correct',
         'extension': '.sql',
         'default': 0,
         'dependencies':[10,11,110,111],
         'desc': 'none'},
     9:  {'name': "average_number_of_attempts",
         'filename': 'populate_feature_9_average_number_of_attempts',
         'extension': '.sql',
         'default': 0,
         'dependencies':[109,202,203],
         'desc': 'none'},
     10: {'name': "sum_observed_events_duration_per_correct_problem",
         'filename': 'populate_feature_10_sum_observed_events_duration_per_correct_problem',
         'extension': '.sql',
         'default': -1,
         'dependencies':[110],
         'desc': 'none'},
     11: {'name': "number_problem_attempted_per_correct_problem",
         'filename': 'populate_feature_11_number_problem_attempted_per_correct_problem',
         'extension': '.sql',
         'default': -1,
         'dependencies':[111],
         'desc': 'none'},
     12: {'name': "average_time_to_sovle_problem",
         'filename': 'populate_feature_12_average_time_to_solve_problem',
         'extension': '.sql',
         'default': -1,
         'dependencies':[112],
         'desc': 'none'},
     14: {'name': "number_of_collaborations",
         'filename': 'populate_feature_14_number_of_collaborations',
         'extension': '.sql',
         'default': 0,
         'dependencies':[],
         'desc': 'none'},
     13: {'name': "observed_event_timestamp_variance",
         'filename': 'populate_feature_13_observed_event_timestamp_variance',
         'extension':  '.py',
         'default': 0,
         'dependencies':[],
         'desc': 'none'},
     15: {'name': "max_duration_resources",
         'filename': 'populate_feature_15_max_duration_resources',
         'extension': '.sql',
         'default': 0,
         'dependencies':[],
         'desc': 'none'},
     16: {'name': "sum_observed_events_lecture",
         'filename': 'populate_feature_16_sum_observed_events_lecture',
         'extension': '.sql',
         'default': 0,
         'dependencies':[],
         'desc': 'none'},
     17: {'name': "sum_observed_events_book",
         'filename': 'populate_feature_17_sum_observed_events_book',
         'extension': '.sql',
         'default': 0,
         'dependencies':[],
         'desc': 'none'},
     18: {'name': "sum_observed_events_wiki",
         'filename': 'populate_feature_18_sum_observed_events_wiki',
         'extension': '.sql',
         'default': 0,
         'dependencies':[],
         'desc': 'none'},
     103:{'name': "difference_feature_3",
         'filename': 'populate_feature_103_difference_feature_3',
         'extension': '.sql',
         'default': 0,
         'dependencies':[],
         'desc': 'none'},
     104:{'name': "difference_feature_4",
         'filename': 'populate_feature_104_difference_feature_4',
         'extension': '.sql',
         'default': 0,
         'dependencies':[],
         'desc': 'none'},
     105:{'name': "difference_feature_5",
         'filename': 'populate_feature_105_difference_feature_5',
         'extension': '.sql',
         'default': 0,
         'dependencies':[],
         'desc': 'none'},
     109:{'name': "difference_feature_9",
         'filename': 'populate_feature_109_difference_feature_9',
         'extension': '.sql',
         'default': 0,
         'dependencies':[],
         'desc': 'none'},
     110:{'name': "difference_feature_10",
         'filename': 'populate_feature_110_difference_feature_10',
         'extension': '.sql',
         'default': 0,
         'dependencies':[],
         'desc': 'none'},
     111:{'name': "difference_feature_11",
             'filename': 'populate_feature_111_difference_feature_11',
             'extension': '.sql',
         'default': 0,
         'dependencies':[],
         'desc': 'none'},
     112:{'name': "difference_feature_12",
             'filename': 'populate_feature_112_difference_feature_12',
             'extension': '.sql',
         'default': 0,
         'dependencies':[],
         'desc': 'none'},
     201:{'name': "number_of_forum_responses",
             'filename': 'populate_feature_201_number_of_forum_responses',
             'extension': '.sql',
         'default': 0,
         'dependencies':[],
         'desc': 'none'},
     202:{'name': "percentile_of_average_number_of_attempts",
             'filename': 'populate_feature_202_percentile_of_average_number_of_attempts',
             'extension':  '.py',
         'default': 0,
         'dependencies':[],
         'desc': 'none'},
     203:{'name': "percent_of_average_number_of_attempts",
             'filename': 'populate_feature_203_percent_of_average_number_of_attempts',
             'extension':  '.py',
         'default': 0,
         'dependencies':[],
         'desc': 'none'},
     204:{'name': "pset_grade",
             'filename': 'populate_feature_204_pset_grade',
             'extension': '.sql',
         'default': 0,
         'dependencies':[205],
         'desc': 'none'},
     205:{'name': "pset_grade_over_time",
             'filename': 'populate_feature_205_pset_grade_over_time',
             'extension': '.sql',
         'default': -1,
         'dependencies':[],
         'desc': 'none'},
     206:{'name': "lab_grade",
             'filename': 'populate_feature_206_lab_grade',
             'extension': '.sql',
         'default': 0,
         'dependencies':[207],
         'desc': 'none'},
     207:{'name': "lab_grade_over_time",
             'filename': 'populate_feature_207_lab_grade_over_time',
             'extension': '.sql',
         'default': 0,
         'dependencies':[],
         'desc': 'none'},
     208:{'name': "attempts_correct",
             'filename': 'populate_feature_208_attempts_correct',
             'extension': '.sql',
         'default': -1,
         'dependencies':[209],
         'desc': 'none'},
     209:{'name': "percent_correct_submissions",
             'filename': 'populate_feature_209_percent_correct_submissions',
             'extension': '.sql',
         'default': 0,
         'dependencies':[],
         'desc': 'none'},
     210:{'name': "average_predeadline_submission_time",
             'filename': 'populate_feature_210_average_predeadline_submission_time',
             'extension': '.sql',
         'default': -1,
         'dependencies':[],
         'desc': 'none'},
     301:{'name': "std_hours_working",
             'filename': 'populate_feature_301_std_hours_working',
             'extension': '.sql',
         'default': 0,
         'dependencies':[],
         'desc': 'none'},
     302:{'name': "time_to_react",
             'filename': 'populate_feature_302_time_to_react',
             'extension': '.sql',
         'default': 0,
         'dependencies':[],
         'desc': 'none'},
}

def returnFeatures():
    return featureDict

def skippedDependencies(featuresToSkip):
    sd = set(featuresToSkip)
    for f in featuresToSkip:
        dependencies = returnFeatures()[f]['dependencies']
        for d in dependencies:
            if d not in sd:
                sd.add(d)
    return sd

def featuresFromFeaturesToSkip(featuresToSkip):
   return sorted([f for f in returnFeatures().keys() if f not in skippedDependencies(featuresToSkip)])
